# Generated by Django 5.0.2 on 2024-04-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_type_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
